# Build settings
markdown: redcarpet
highlighter: pygments


# Site settings
title: "JCE Manager"
description: > # this means to ignore newlines until "email:"
   Free Your Academic Data

url: "" # the base hostname & protocol for your site
fullurl: http://liranbg.github.io/JceManager
baseurl: /JceManager

email: sagidayan@gmail.com
#blog logo
logo: "/JceManager/assets/images/logo.png"
# blog cover
cover: "/JceManager/assets/images/background_image.jpg"

name: 'JCE Manager'
author: 'JCE Manager Teem'
author_image: "/JceManager/assets/images/author.jpg"

paginate: 5


# social icons and sharing options
social:
  # - icon:	twitter
  #   url:	https://twitter.com/dirkfabisch
  #   desc: Follow me on twitter
  #   share_url: http://twitter.com/share
  #   share_title: ?text=
  #   share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/liranbg/JceManager
    desc:	Fork me on github!
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
#    
# Members information. Shown on About page.
members:
  - name: Liran Ben Gida
    position: Project Manager
    text: "After two semesters and 12 courses, I was thinking why can't I see my AVG on each single semester? Why do I need to calculate 12 different courses to know if I have to take another exam to raise my average. These thoughts translated into code in a month,And after Sagi joined me, with his driven, I turned my though into a real project."
    img: liran.jpg
    social:
      - title: envelope #use for email address
        url: mailto:liranbg@gmail.com
        tooltip: e-mail
      - title: facebook
        url: https://www.facebook.com/liranbg
        tooltip: Facebook Profile
      - title: github
        url: http://www.github.com/liranbg
        tooltip: github Profile
  - name: Sagi Dayan
    position: Developer And Website Maintainer
    text: "I just wanted to get my Semester into my Google account in one click. After a 10 min break between classes Liran & I thought it might be cool to join forces. After tow mothes we got a CLI program, and it got us evan hungriear. This Project will be our little baby, And Baybies need to grow..." 
    img: sagi.jpg
    social:
      - title: envelope #use for email address
        url: mailto:sagidayan@gmail.com
        tooltip: e-mail
      - title: linkedin
        url: http://lnkd.in/dFXupGn
        tooltip: Linkedin Profile
      - title: github
        tooltip: github profile
        url: http://www.github.com/sagidayan
      - title: google-plus
        url: https://plus.google.com/+SagiDayan
        tooltip: Google+ Profile
